[package]
name = "cpf-generator"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
